[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
wager_program = "8PRQvPo16yG8EP5fESDEuJunZBLJ3UFBGvN6CKLZGBUQ"

[programs.devnet]
wager_program = "8PRQvPo16yG8EP5fESDEuJunZBLJ3UFBGvN6CKLZGBUQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/index.ts"
